.. _CreateandManageConfigurations:

Create & Manage Configurations
================================

A configuration is the means by which an instrument is described and defined to IBEX.  A configuration defines the blocks, IOCs, components, macros and other items which IBEX needs to use in order to control the instrument.  You can create multiple configurations for an instrument, to describe and define how the instrument has been set up for different experiments.

**Please note:** An IBEX configuration is **not** the same as a Mantid configuration.  IBEX and Mantid view instruments in fundamentally different ways, which means that their respective configurations are not interchangeable.

Creating a Configuration
------------------------

To create a configuration:

#. Select ``Configurations > New`` from the ``Configuration`` menu.
#. IBEX displays a dialog containing eight tabs.  

   #. IOCs
   #. Blocks
   #. Groups
   #. Components
   #. IOC Macros
   #. IOC PV Values
   #. IOC PV Sets
   #. Summary

We'll describe each of these in turn.

IOCs Tab
~~~~~~~~
The IOCs tab lists all the IOCs available on the instrument.  In general, you will only wish to include a sub-set of these in your configuration (i.e. those that correspond to devices on your instrument).

To include an IOC in your configuration, scroll down the list until you find the appropriate IOC and select the Auto-Start or Auto-Restart check-boxes (or select both).  By selecting these check-boxes, IBEX will automatically start (or restart) to chosen IOCs each time your configuration is loaded into IBEX.

**Note:** The list of IOCs in the IOC tab also includes a column headed Sim. level.  This column is used to indicate whether the IOC should run in simulation mode.  By default, the Sim. level file is set to NONE, meaning that the IOC will not run in simulation mode.

Blocks Tab
~~~~~~~~~~
The Blocks tab lists all the blocks that have been defined for the current configuration.  When creating a new configuration, the list of blocks will be empty.  A block is, essentially, an alias to a PV ([[ProcessVariables]]).

To create a new block, click on the ``Add Block`` button.  IBEX displays a dialog to allow you to define the new block.  By default, the new block is given the name ``NEW_BLOCK``.  You can give the block any name you like, provided the name starts with a character and contains only the characters a-z and A-Z, the digits 0-9 and the underscore character.

Below the block name field is the PV address field.  Click on the ``Select PV`` button next to the PV address field to choose a PV to be aliased by the block name.

On clicking the ``Select PV`` button, IBEX will display a list of PVs available on your instrument.  There can be a very large number of PVs on an instrument, so the dialog provides a number of filters to help you narrow your search.  Choose:

PVs from
   ``All IOCs`` to see PVs from all IOCs on your instrument (this can result in a very long list of PVs).

   ``Active IOCs`` to see PVs only from IOcs that are currently running on your instrument.

   ``Config IOCs`` to see PVs only from IOCs that are included in the current configuration.

Interest Level
   ``High`` to see PVs considered to be of high interest to scientists

   ``Medium`` to see PVs considered to be of medium interest to scientists (many PVs in this category will be of more interest to technicians and support staff, rather than scientists)

   ``Facility`` to see PVs that relate to facility, rather than instrument, devices (PVs in this category typically include PVs relating to the accelerator, target stations, shared beamlines and instrument shutters).

   ``All`` to see all PVs from your selected category of IOCs (again, this can generate a very long list of PVs).

Scroll down the list of PVs until you find the one you want.  Click on it, to select it and then click on the OK button to return to the Add Block dialog.

On the Add Block dialog you can also choose to 

Visible/Local
   Toggle the ``Visible`` check-box to make the block visible or hidden.  By default, blocks are always visible.  This feature is useful, for example, if you need to see blocks while setting up an experiment, but don't need to see them once the experiment is running.

   The ``Local`` check-box is used when you need to view PVs from another instrument as blocks.  In most circumstances, you will not need to view PVs belonging to another instrument, so you should leave the ``Local`` check-box checked.  Facility PVs are an exception to this rule, but IBEX knows about facility PVs and, in this case, automatically sets the ``Local`` check-box  to unchecked.  If you do need to view PVs belonging another instrument, please consult with the Experiment Controls team.

Run-Control Settings
   Toggle the ``Enabled`` check-box to enable run-control on this block.  Use the Low Limit and High Limit fields to define the run-control range (i.e. data is collected only when the block lies within the range) .

Logging Settings
   By default (Logging Settings is disabled), the block is logged whenever its value changes.  Toggle the ``Enabled`` check-box to change the way the block is logged.  You can set the block to logged periodically (i.e. every N seconds), or you can set a "deadband" - the block will only be logged if its value falls outside +/- the limit defined by the deadband value.

Groups Tab
~~~~~~~~~~
Use the Groups tab to arrange your blocks into convenient groups.  You can define as many groups as you wish and you can place as many blocks in each group as you wish, although a block can only appear in one group.

By default, all blocks are assigned to an automatic group called "Other".  By creating new groups, you have the opportunity to override the default assignment and assign blocks to groups of your choosing.  

To create a new group, select the Groups tab and click on the ``Add`` button.  IBEX displays a dialog to allow you to define a new group.  By default, the new block is given the name ``NEW_GROUP``.  You can give the block any name you like, provided the name starts with a character and contains only the characters a-z and A-Z, the digits 0-9 and the underscore character.  When you click on the ``Add`` button, the dialog displays which blocks are available to be assigned to the new group (i.e. blocks in the "Other" group).

Use the buttons with the Up and Down arrows to control the ordering of the groups and the order of the blocks within the groups.

Components Tab
~~~~~~~~~~~~~~

Components are, in essence, sub-configurations.

**TO DO**

IOC Macros
~~~~~~~~~~

IOC Macros are configurable values that IBEX can supply to the IOC when the IOC is started.  For example, if the IOC is controlling a serial device attached to a COM port, you can use an macro to identify the appropriate port to the IOC.  This is especially useful if the device moves between instruments and may be attached to different COM ports on different instruments.  Another example of an IOC macro might be the name of a calibration file.

To set an IOC macro:

#. Select the IOC Macros tab and choose an IOC from the drop-down menu list of IOCs.  If the IOC has any configurable macro parameters, they will be displayed in the table below.  The table contains four columns:

   #. Macro Name: the name of the macro (e.g. ``PORT``, ``BAUD`` or ``IPADDRESS``)
   #. Value: the current value of the macro (e.g. ``COM3``, ``9600`` or ``192.83.42.106``)
   #. Description: a short description of the macro's purpose
   #. Pattern: macro values need to be defined correctly.  IBEX uses the pattern to validate the macro value. (For those familiar with such things, the pattern is expressed as a "regular expression").

#. Choose a macro from the table.  The ``Name:`` field (read-only) is populated with the macro name and the ``Value:`` field is populated with the current value of the macro.

#. Edit the ``Value:`` field to change the macro value.  Please note that the value you enter will be validated against the pattern.  If the macro does not conform to the pattern, IBEX will display a warning message.  IBEX will refuse to accept any values that do not conform to the pattern.

#. Click on the ``Set Macro`` button to set the macro value.  The table of macros will be updated with the new value.  You can also use the ``Clear Macro`` button to clear the contents of the ``Value:`` field.

If you are not sure about how to correctly configure macro values for a device, please consult with the Experimental Controls team.

IOC PV Values
~~~~~~~~~~~~~

**TO DO**

IOC PV Sets
~~~~~~~~~~~

**TO DO**

Summary
~~~~~~~

The Summary tab allows you to create a short description for your configuration.  It also allows you to associate a default synoptic view with your configuration.

When you click on the Summary tab, IBEX displays the following fields:

Name
   This is a read-only field.  It is defined when you save the configuration.  When you are creating a new configuration, the ``Name:`` field will be empty.

Description
   Provide a short description of your configuration.  Configuration names can sometime be a little cryptic; a short description will help you to better remember the purpose of the configuration.

Synoptic
   IBEX allows you to create different synoptic views for use with different configurations.  Therefore, it is convenient to associate a synoptic view with a configuration - it saves you from having to remember the association.  Your chosen synoptic will be used as the default synoptic whenever you use this configuration.  

