.. _CreateandManageSynoptics:

Create & Manage Synoptic Views
==============================

In IBEX, synoptic views provide you with interactive, schematic views of your instrument.  Each icon on a synoptic view represents a device attached to your instrument.  You can tailor the synoptic view to display key PVs next to the device icons.   By double-clicking on an item, you can drill down to see more detail.

You can define as many synoptic views as you wish for your instrument.  

A synoptic need not encompass the whole instrument.  You can define synoptic views that focus on specific aspects of your instrument - for example, just the beam optics, or just the sample stack and equipment mounted on the sample stack.

You can also associate a synoptic view with a particular configuration, so that, in effect, the chosen synoptic becomes the default synoptic for that configuration.

Creating a Synoptic View
------------------------

To create a synoptic view:

#. Select ``New`` from the ``Synoptic`` menu.
#. IBEX displays the Synoptic editor dialog, which is divided into four panes.  

   #. Instrument Tree
   #. Component Details
   #. Component  Target Details
   #. PV Details

#. At the bottom of the dialog are three buttons

Synoptic Preview
   Click on the ``Synoptic Preview`` button to get a preview of how your synoptic will appear.  You can click on the ``Synoptic Preview`` button at any time.

Save as...
   Click on the ``Save as...`` button to save your changes.  You must provide a name for the synoptic view.  The name of the synoptic can contain only the characters a-z, A-Z, 0-9 and _ (underscore).  The name must also start with a character.

Cancel
   Click on the ``Cancel`` button to exit the dialog without saving your changes.

Use the Synoptic editor as follows:

#. Click on the ``Add Component`` button to add a new component to the Instrument Tree.

   #. When you add a new component, its details are shown in the Component Details pane.  It is given the default name ``New Component`` and a default type of ``UNKNOWN``.  
   #. In the Component Details pane, you can adjust the general properties of the component.

      * Give it a suitable name
      * Select the type of device it represents.  Click on the drop-down menu to select the device type.
      * Add associated PVs to be displayed below the component in the synoptic view (``Add New PV`` button).
      * Remove associated PVs 

   #. If you add an associated PV (using the ``Add New PV`` button), its details appear in the PV Details pane.  Use the the ``Select Block`` or ``Select PV`` buttons to choose a block or PV.

   #. Use the Component Target Details pane to adjust the specific properties of the component (e.g. which model of device the component represents, which component properties are needed).

      * The `name:` field is a drop-down menu.  Select the name/model of the device.  Some names on the list refer to general classes of device (e.g.`Eurotherm` refers to all Eurotherm temperature controllers); other names refer to specific models (e.g. `Julabo FP300` refers to a specific model of Julabo water bath).  Whether a name is general or specific depends on the manufacturer of the device.  When you have made your selection, a short description of the component will be displayed in the `Description:` field.
      * If you are not sure which name/model to select for the `Name:` field, click on the `Default Target` button.  IBEX will then display a list of names/models filtered by the Component Type field (see Component Details pane).  This will significantly reduce the size of the list (often there will be only one choice).  Choose the most appropriate name/model.
      * Clicking on the `Clear Target` button will clear any selection in the `Name:` field.
      * Below the `Description:` field is a table of `Properties:`, which lists the properties belonging to the selected component.  Each property has a name and a value.  Select each property in turn to edit the value.
      * On selecting a property, the value of the property will  appear `Value:` field.  A description of the value is provided in the `Description:` field below the `Value:` field.  The default value might be blank.
      * Set the property value.   
      * **Please note:** Component properties are very specific to individual devices - it is impractical to give definitive advice in a user manual as to correct value for a compoenent property .  The  `Description:` field will generally provide advice on the type of value to be entered in the `Value:` field.  If y
      * Remove associated PVs 

#. Click on the ``Copy Component`` button to duplicate the currently selected component.  If no component is selected, the ``Copy Component`` button is inactive.

#. Click on the ``Delete Component`` button to delete the currently selected component.  If no component is selected, the ``Delete Component`` button is inactive.

#. Toggle the ``Show Beam`` check-box to show or hide the schematic representation of the beam in the synoptic view.  By default, the beam will be shown.

