IBEX FAQ
========

In this section of the IBEX user manual we have compiled a list of frequently asked questions.  If you have a question about IBEX that is not answered below, please let us (the Experimental Controls team) know.  If your question is likely to be asked by others, we'll add it to the list.

List of Frequently Asked Questions
----------------------------------

.. _Return:

#. `How do I report a problem with IBEX?`_
#. `How do I install IBEX Server?`_
#. `How do I install IBEX Client?`_
#. `How do I start IBEX Server?`_
#. `How do I stop IBEX Server?`_
#. `Can I run IBEX and SECI at the same time?`_
#. `This is the seventh question`_
#. `This is the eighth question`_
#. `This is the ninth question`_
#. `This is the tenth question`_

.. _`How do I report a problem with IBEX?`:  

**Q: How do I report a problem with IBEX?**

**A:** To report a problem with IBEX (Client or Server), please use the `Instrument Problem/Bug Report <http://sparrowhawk.nd.rl.ac.uk/footprints/?product=PC%20Instrument%20Control&amp;format=pcinst>`_ page.  Using this page helps to ensure that your problem report gets routed to the right person as quickly as possible.  When reporting a problem, it is helpful to include the version numbers of your IBEX Client and Server in your report.  To view the version numbers select ``Help > About`` from the menu bar in the IBEX Client.

Return_

.. _`How do I install IBEX Server?`:

**Q: How do I install IBEX Server?**

**A:** To install IBEX Server - see [[InstallingIBEX]]

Return_

.. _`How do I install IBEX Client?`:

**Q: How do I install IBEX Client?**

**A:** To install IBEX Client - see [[InstallingIBEX]]

Return_

.. _`How do I start IBEX Server?`:

**Q: How do I start IBEX Server?**

**A:** To start IBEX Server - see [[StartingAndStoppingIBEX]]

Return_

.. _`How do I stop IBEX Server?`:

**Q: How do I stop IBEX Server?**

**A:** To stop IBEX Server - see [[StartingAndStoppingIBEX]]

Return_

.. _`Can I run IBEX and SECI at the same time?`:

**Q: Can I run IBEX and SECI at the same time?**

**A:** In a word - No.  Running two control programs on any system is a bad idea - which program has control?  If you were to run IBEX and SECI on the same system, the two would contend for control of individual devices.  It would not be clear which device was controlled by which program.  The results would be unpredictable.

Return_

.. _`This is the seventh question`:

This is the seventh answer.

Return_

.. _`This is the eighth question`:

This is the eighth answer.

Return_

.. _`This is the ninth question`:

This is the ninth answer.

Return_

.. _`This is the tenth question`:

This is the tenth answer.

Return_
