Starting a scripting session
============================

From IBEX
---------

The best way to run ``genie_python`` commands is from the scripting perspective of the IBEX client.

To open a scripting window:

1. Start the IBEX client
2. Open the scripting perspective

.. image:: genie_python_and_ibex/OpenTheScriptingPerspective.png

3. From here, you can start entering Python code. It will be executed line by line as you enter it.

Outside IBEX
------------

You can also open a scripting terminal by running ``C:\Instrument\Apps\Python\genie_python.bat`` but this is recommended for advanced users only.

**Exercise 1**
==============

- Open a scripting window in IBEX
- Output "Hello, world!" to the console
- Output the square of all the integers between 1 and 10

[[Solution|genie_python-and-IBEX-(Exercise-solutions)]]

-------------------------------------------------------------------------------

**Next**: [[Common commands|genie_python-and-IBEX-(Common-commands)]]

**Previous**: [[Course introduction|genie_python-and-IBEX-(Introduction)]]