Welcome to IBEX User Manual's documentation!
============================================

.. toctree::
    :maxdepth: 2
    :numbered:
    :titlesonly:
    :hidden:
    
    Introduction/WhatIsIBEX.rest
    Introduction/StartingAndStoppingIBEX.rest
    Concepts/ProcessVariables.rest
    Concepts/Blocks.rest

* :ref:`WhatIsIBEX`
* :ref:`StartingAndStoppingIBEX`
* :ref:`ProcessVariables`
* :ref:`Blocks`

* `test web link <http://www.isis.stfc.ac.uk/>`_
* <http://www.isis.stfc.ac.uk/>

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

test2

[[What is ibex|Introduction/WhatIsIBEX.rest]]
