Welcome to IBEX User Manual's documentation!
============================================

.. toctree::
    :maxdepth: 2
    :numbered:
    :titlesonly:
    :hidden:
    
    Introduction/WhatIsIBEX.rest
    Introduction/StartingAndStoppingIBEX.rest
    Concepts/ProcessVariables.rest
    Concepts/Blocks.rest

:ref:`what_is_ibex`

Indices and tables
==================

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`

