In this section of the IBEX User Manual, we describe how to do the most common and important tasks.

[[Create and Manage Configurations|CreateAndManageConfigurations]]

[[Create and Manage Components|CreateandManageComponents]]

[[Start and Stop IOCs|StartandStopIOCs]]

[[Navigate Synoptics|NavigateSynoptics]]

[[Create and Manage Synoptics|CreateandManageSynoptics]]

[[Craete and Manage Device Screens]]

[[Manage the DAE|ManagetheDAE]]

[[Plot a Block Graph|PlotaBlockGraph]]

[[Create PVs for generic user data|How-to-create-PVs-for-generic-user-data]]
