IBEX GUI Features
=================

.. image:: ibex_client_e4_zoom.png

This section summarises the main features of IBEX as presented by the IBEX GUI client.

You might find it helpful to refer to a `schematic view of the IBEX UI <http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/IBEX%20E4%20schematic.png>`_ while reading this section.

[[Menu Bar|MenuBar]]

[[Dashboard]]

[[Blocks and Groups|BlocksandGroups]]

[[Views]]

[[Banner|Banner]]