Open Genie: Compare and contrast
================================

Commands
--------

The majority of ``OpenGENIE`` instrument control commands have a very close equivalence in ``genie_python``.

For example, the ``OpenGENIE`` command::

    BEGIN

in ``genie_python`` becomes::

    g.begin()

Similarly, the ``OpenGENIE`` command::

    CHANGE TITLE="New title"

in ``genie_python`` becomes::

    g.change_title("New title")

or alternatively::

    g.change(title="New title")

Similarly, most arguments will be very similar between ``OpenGENIE`` and ``genie_python``. For example, the following ``OpenGENIE`` command::

    CSET/CONTROL TEMP1=5 LOWLIMIT=1 HIGHLIMIT=10

becomes the following in ``genie_python``::

    g.cset(TEMP1=5, runcontrol=True, lowlimit=1, highlimit=10)

**NOTE** Python is case sensitive and the arguments, apart from the block name, are in lower case

Worked example
--------------

Take the following sequence of ``OpenGENIE``



Procedures vs. functions
------------------------

Loops
-----

-------------------------------------------------------------------------------

**Previous**: [[Scripting|Ibex-and-genie_python:-Scripting]]

**Next**: [[Exercise solutions|Ibex-and-genie_python:-Exercise-solutions]]
   