Open Genie: Compare and contrast
================================

Commands
--------

The majority of ``OpenGENIE`` instrument control commands have a very close equivalence in ``genie_python``.

For example, the ``OpenGENIE`` command::

    BEGIN

in ``genie_python`` becomes::

    g.begin()

Similarly, the ``OpenGENIE`` command::

    CHANGE TITLE="New title"

in ``genie_python`` becomes::

    g.change_title("New title")

or alternatively::

    g.change(title="New title")

Notably, ``genie_python`` does not cover data analysis. If you wish to do analysis in Python there are several options available:

- Python: The base Python language is very powerful and can do a lot of common mathematical functions. In particular, refer to the ``math`` module.
- Numpy: This is a numerical analysis module that is very powerful and comes bundled with the distribution of ``genie_python``
- Mantid: This has extensive coverage of the tools required by neutron and muon experiments. We will not cover it in this course but there is dedicated training available from the Mantid team if you'd like to learn more.

Worked example
--------------

Take the following sequence of ``OpenGENIE``



Procedures vs. functions
------------------------

Loops
-----

-------------------------------------------------------------------------------

**Previous**: [[Scripting|Ibex-and-genie_python:-Scripting]]

**Next**: [[Exercise solutions|Ibex-and-genie_python:-Exercise-solutions]]
   