Exercise 1
==========

From [[Getting Started|Ibex-and-genie_python:-Getting started]].

-   *Open a scripting window in Ibex*

    - Should be straightforward if Ibex is correctly installed.
    - Ideally the instrument will appear as ``SETUP``
    - The output when the scripting window opens should look a bit like this:

.. image:: StandardStartupOutputOnDemo.png

-   Output "Hello, world!" to the console

    - Enter something like ``print "Hello, World!`` and press return

-   Calculate and output the square of all the integers between 1 and 10

    - This is best achieved with the following loop::

        for i in range(1,11):
            print i*i

    - A **blank line** will indicate to the scripting window that you've finished writing the loop and it can go ahead and be executed.

Exercise 2
==========

From [[Common commands|Ibex-and-genie_python:-Common-commands]]