IBEX GUI Features
=================

This section summarises the main features of IBEX as presented by the IBEX GUI client.

You might find it helpful to refer to a `schematic view of the IBEX UI 
.. image:: IBEX%20E4%20schematic.png
  :target: http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions

while reading this section.

[[Menu Bar|MenuBar]]

[[Dashboard]]

[[Blocks and Groups|BlocksandGroups]]

[[Views]]

[[Banner|Banner]]

Below is a screenshot of the IBEX GUI:

.. image:: ibex_client_e4_zoom.png