There are many motors on IMAT this page contains some details about what happens if there is a power cut.

Jaws
----

There are jaws on Galil 1 (axis 5,6,7,8) and then all axes on Galil controllers 2 and 3. These all have homing routines and can be homed together (there is a script :code:`g.home_`) which will home all axis. If the axis appears not to move the IOC should be restarted; this will reload programs and settings into the Galil controller.

Sample Stack
------------

The sample stack Sample Stack X and Sample Stack Y use absolute encoders. After a power cut the IOC should be restarted and then it needs to be reset. Currently to do this drill down to the more details level and then click ueip (use encoder if present) No then yes. This resets the motor steps in the Galil controller and thus allows the motor to move.

