.. _InstallingIBEX:

Installing IBEX
===============

Installing IBEX Server
----------------------

Installation of IBEX server on an instrument control PC is a moderately complex task, requiring the installation and configuration of several software components.  If you need to install IBEX server on your instrument, please contact the Experimental Controls team.

Installing IBEX Client
----------------------

Installation of IBEX client on a PC is simple and straightforward.

Pre-requisites for running IBEX Client
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In order to run IBEX client, your PC must meet the following pre-requisites

#. Your PC must be running Windows 7 (Professional or Enterprise), Service Pack 1 or Windows 10 (Professional or Enterprise), Build 10586.
#. Your PC must also be running an up-to-date version of Java version 8, update 101 (or later). If you need to install an up-to-date version of Java, you can obtain a copy from the Java web-site (http://www.java.com/en/).  Please be sure to choose the 64-bit version of Java.

Installation
~~~~~~~~~~~~

1. Open a command window on your PC and use the following commands to create the 
   following folders on your ``C:`` drive:

::

      mkdir C:\Instrument\Apps\Client
      mkdir C:\Instrument\Apps\Python
      cd C:\Instrument

2. In the command window type the following (if your command prompt doesn't support UNC paths, 
   use ``pushd`` instead of ``cd``):

::

      cd \\isis\inst$\Kits$\CompGroup\ICP\Releases

3. Inside this folder you will see folders with names of the form ``BUILDmmm``, where ``mmm`` is a 
   three-digit number and folders with names of the form ``BUILD-nnnn``, where ``nnnn`` is a four-digit 
   number. Change directory to the folder ``BUILDmmm`` with the highest value of ``mmm``.

4. Run the command ``install_client.bat``. This will copy the contents of the above directory 
   to ``C:\Instrument\Apps\Client``. It will also install genie_python.

5. You might find it convenient to create a desktop shortcut to use to launch the IBEX client.
