Contents
========

Starting a scripting session
============================

The best way to run ``genie_python`` commands is from the scripting perspective of the Ibex client.

To open a scripting window:

1. Start the Ibex client
2. Open the scripting perspective

::
    IMAGE: OpenTheScriptingPerspective

**Exercise 1**
--------------
- Open a scripting window in Ibex
- Output "Hello, world!" to the console
- Calculate and output the square of all the integers between 1 and 10

You can also open a scripting terminal by running ``C:\Instrument\Apps\Python\genie_python.bat``. This will not provide some advanced features such as auto-complete though, and is recommended for advanced users only.


Accessing ``genie_python`` commands
===================================

Basic commands
==============

Instrument control
------------------

Blocks
------

Run control
-----------

Experiment setup
----------------


Creating and running scripts
============================

Instrument scripts
------------------

Create
~~~~~~

Run
~~~

User scripts
------------

Create
~~~~~~

Run
~~~

Open Genie: Compare and contrast
================================

Commands
--------

Arguments
---------

Procedures vs. functions
------------------------

Loops
-----

Exercise notes
==============

Exercise 1
----------
- Open a scripting window in Ibex
    - Should be straightforward if Ibex is correctly installed.
    - Ideally the instrument will appear as ``SETUP``
    - The output when the scripting window opens should look a bit like this:
::
    IMAGE: StandardStartupOutputOnDemo
- Output "Hello, world!" to the console
    - Enter something like ``print "Hello, World!`` and press return
- Calculate and output the square of all the integers between 1 and 10
    - This is best achieved with the following loop:
::
    for i in range(1,11):
        print i*i

    - A **blank line** will indicate to the scripting window that you've finished writing the loop and it can go ahead and execute it