.. image:: LiveView.png

You instrument may have access to LiveView - a way to see event data from the DAE in real time. This option is available through an OPI which you can set up in the Device Screen View if your instrument is set up for LiveView.