.. _ManagetheDAE:

Manage the DAE
==============

The Data Acquisition Electronics (DAE) is the hardware where the neutron or muon data is collected. The DAE is controlled by the ICP (see [[Key Concepts in IBEX|KeyConceptsinIBEX]]), which informs the DAE when to start and stop collecting data from the instrument detectors. The ICP also receives sample environment information and combines it with the detector data and is responsible for transferring the final combined dataset to a data file.

The DAE view communicates with the ICP to control the DAE.

Contents
--------

#. `Run Summary`_
#. `Experiment Setup`_

   #. `Time Channels`_
   #. `Data Acquisition`_
   #. `Periods`_

#. `Run Information`_
#. `Spectra Plots`_
#. `Diagnostics`_
#. `Vetos`_

Run Summary
-----------

The Run Summary tab displays some summary information about the current run and displays any log messages received from the ICP. 

Run Summary Fields
~~~~~~~~~~~~~~~~~~

* ``Instrument``: (read-only) records the instrument on which the current run is being performed
* ``Run Status``: (read-only) records status of the current run
* ``Run Number``: (read-only) records the current run number
* ``ISIS Cycle``: (read-only) records the current ISIS cycle
* ``Title``: you can provide a short description of the current run in the ``Title`` field.  Click on the ``Set`` button to commit the change (i.e. send it to the ICP, so that it gets included in the data file).
* The ``Show Title in Dataweb Dashboard Page`` check box allows you to toggle the display of the title in the Dataweb dashboard.  This checkbox only affects the Dataweb dashboard; it does not affect display of the title in IBEX, or the inclusion of the title in the data file.

Return to `Contents`_.

Message Log
~~~~~~~~~~~
The message log area lets you view any messages issued by the ICP.  The message log area is the same as the main Log Messages view, filtered to show only messages from the ICP.

The Run Summary tab also provides a number of buttons to control the acquisition of data.

Begin Run
   Click on the ``BEGIN RUN`` button to start a new run.  Beginning a run instructs the ICP to tell the DAE to start collecting data. The DAE’s run status will change to RUNNING (which is reflected in the ``Run Status`` field and in the IBEX [[Dashboard]].

End Run
   Click on the ``END RUN`` button to terminate the current run.  Ending a run instructs the ICP to tell the DAE to stop collecting data.  It also instructs the ICP to write the data collected during the run to a file. The DAE’s run status will change to SETUP.

Pause Run
   Click on the ``PAUSE RUN`` button to halt (but not end) the current run.  Pausing a run instructs the ICP to tell the DAE to pause data collection indefinitely. The DAE’s run status will change to PAUSED.  The DAE's status will remain PAUSED until it is instructed to RESUME.

Resume Run
   Click on the ``RESUME RUN`` button to resume a previously paused run.  Resuming a run instructs the ICP to tell the DAE to resume data collection after it has been paused. The DAE’s run status will return to RUNNING.

Abort Run
   Click on the ``ABORT RUN`` button to abort the current run.  Aborting a run instructs the ICP to tell the DAE to stop data collection (as for END).  However, the data that has been collected is not written to a file; if a new run is started, then any data that has been collected will be lost. The DAE’s run status will change to SETUP.

Cancel Abort 
   Click on the ``CANCEL ABORT`` button to cancel the abort process.

Save Run 
   Click on the ``SAVE RUN`` button to save the current run.

Return to `Contents`_.


Experiment Setup
----------------

The Experiment Setup comprises three sub-tabs.  Each of these 3 sub-tabs will have been configured by an ISIS Instrument Scientist.  Please do not modify the contents of these 3 tabs without consulting with the instrument scientist.

Time Channels
~~~~~~~~~~~~~

The time channels tab allows the setting of the spectra captured in different time regimes. By setting different step sizes and size distributions (using mode) you can optimise the time bins in the final spectra. The time channels can be set using the table below or if more regimes are required a file can be specified. The files are part of the settings stored in the `configurations/tcb` directory.

Return to `Contents`_.

Data Acquisition
~~~~~~~~~~~~~~~~

The data acquisition tab allow you to set up how the data is collected. The wiring table, detector table and spectra table can be set so that the DAE knows how to collect data from the detectors and turn it into spectra. These files are part of the settings stored in the `configurations/tables` directory.
The vetos section allows different vetos to be turned on.
The muon section allows the DAE to collect muon data.
The Timing section allows timing source and auto save frequency to be set.

Return to `Contents`_.

Periods
~~~~~~~

The period tab allows the period types and needed parameters to be setup within the DAE. Periods allow data to be collected as if restarting the DAE but without the time overhead of doing this. Software periods are controlled via software command, e.g. genie_python's `change_period` command. The other options are Harware controlled and these are internal (within the DAE) or external control. 

Return to `Contents`_.

Run Information
---------------

The Run Information Tab provides a more compete summary of the DAE setup than the Run Summary tab.  All the fields on this tab are read-only.

Return to `Contents`_.

Spectra Plots
-------------

The Spectra Plots Tab displays up to 4 spectra plots.  The plots show the recorded spectra from the detectors which were setup using the tables in the data acquisition tab.  You can choose which spectra are plotted by using the ``Spectrum:`` and ``Period:`` fields for each plot.  Click on the ``Set Plot`` button (positioned at the top right of each plot) to update the plot after changing the ``Spectrum:`` or ``Period:`` fields.


Return to `Contents`_.

Diagnostics
-----------

Return to `Contents`_.

Vetos
-----

The Vetos tab shows a summary of the vetoes that are in force for the current run.  This information is read-only.  Vetoes can only be changed prior to the start of a run, via the `Data Acquisition`_ sub-tab on the `Experiment Setup`_ tab.

Return to `Contents`_.
