.. _ManagetheDAE:

Manage the DAE
==============

The Data Acquisition Electronics (DAE) is the hardware where the neutron or muon data is collected. The DAE is controlled by the ICP, which informs the DAE when to start and stop collecting data from the instrument detectors. The ICP also receives sample environment information and combines it with the detector data and is responsible for transferring the final combined dataset to a data file.

The DAE view communicates with the ICP to control the DAE.

Contents
--------

#. `Run Summary`_
#. `Experiment Setup`_

   #. `Time Channels`_
   #. `Data Acquisition`_
   #. `Periods`_

#. `Run Information`_
#. `Spectra Plots`_
#. `Diagnostics`_
#. `Vetos`_

Run Summary
-----------

The Run Summary tab displays some summary information about the current run and displays any log messages received from the ICP. 

Run Summary Fields
~~~~~~~~~~~~~~~~~~

* ``Instrument``: (read-only) records the instrument on which the current run is being performed
* ``Run Status``: (read-only) records status of the current run
* ``Run Number``: (read-only) records the current run number
* ``ISIS Cycle``: (read-only) records the current ISIS cycle
* ``Title``: you can proviode a short description of the current run in the ``Title`` field.  Click on the ``Set`` button to commit the change (i.e. send it to the ICP, so that it gets included in the data file).

Message Log
~~~~~~~~~~~
The message log area lets you view any messages issued by the ICP.  The message log area is the same as the main Log Messages view, filtered to show only messages from the ICP.

The Run Summary tab also provides a number of buttons to control the acquisition of data.

Begin Run
   Click on the ``BEGIN RUN`` button to start a new run.  Beginning a run instructs the ICP to tell the DAE to start collecting data. The DAE’s run status will change to RUNNING (which is reflected in the ``Run Status`` field and in the IBEX [[Dashboard]].

End Run
   Click on the ``END RUN`` button to terminate the current run.  Ending a run instructs the ICP to tell the DAE to stop collecting data.  It also instructs the ICP to write the data collected during the run to a file. The DAE’s run status will change to SETUP.

Pause Run
   Click on the ``PAUSE RUN`` button to halt (but not end) the current run.  Pausing a run instructs the ICP to tell the DAE to pause data collection indefinitely. The DAE’s run status will change to PAUSED.  The DAE's status will remain PAUSED until it is instructed to RESUME.

Resume Run
   Click on the ``RESUME RUN`` button to resume a previously paused run.  Resuming a run instructs the ICP to tell the DAE to resume data collection after it has been paused. The DAE’s run status will return to RUNNING.

Abort Run
   Click on the ``ABORT RUN`` button to abort the current run.  Aborting a run instructs the ICP to tell the DAE to stop data collection (as for END).  However, the data that has been collected is not written to a file; if a new run is started, then any data that has been collected will be lost. The DAE’s run status will change to SETUP.

Cancel Abort 
   Click on the ``CANCEL ABORT`` button to cancel the abort process.

Save Run 
   Click on the ``SAVE RUN`` button to save the current run.


Experiment Setup
----------------

Time Channels
~~~~~~~~~~~~~

Data Acquisition
~~~~~~~~~~~~~~~~

Periods
~~~~~~~

Run Information
---------------

The Run Information Tab provides a more compete summary of the DAE setup than the Run Summary tab.  All the fields on this tab are read-only.

Spectra Plots
-------------

Diagnostics
-----------

Vetos
-----

Some stuff here ...
