.. _NavigateSynoptics:

Navigating Synoptic Views
=========================

In IBEX, synoptic views provide you with interactive, schematic views of your instrument.  Each icon on a synoptic view represents a device attached to your instrument.  You can tailor the synoptic view to display key PVs next to the device icons.  By double-clicking on an item, you can drill down to see more detail.

The focus of this page is navigating synoptic views.  If you wish to create your own synoptic view see [[CreateandManageSynoptics]].


Contents
--------

#. `Selecting a Synoptic View`_
#. `Navigating a Synoptic View`_

Selecting a Synoptic View
-------------------------

#. To view an instrument synoptic, click on the ``Synoptic`` button on the View Selector (see [[Views]]).
#. If a default synoptic has been defined for your current configuration, IBEX will display it.  The name of the synoptic will be displayed in the drop-down menu in the area labelled ``Synoptic Selection`` at the top of the synoptic display area.
#. If no default synoptic has been defined for your current configuration, IBEX will display ``--NONE--`` in the drop-down menu in the area labelled ``Synoptic Selection`` at the top of the synoptic display area and the synoptic display will be blank. 
#. You can choose to view any synoptic defined for your instrument by in the drop-down menu in ``Synoptic Selection`` area and choosing any of the synoptics listed.  IBEX will refresh the synoptic display to show your chosen synoptic.

Return to `Contents`_.

Navigating a Synoptic View
--------------------------

Return to `Contents`_.

