IBEX provides a quick, easy way to plot a graph of a block or PV as a function of time (i.e. a "strip-chart").

Plot a Graph of a Block
-----------------------

To plot a graph of a block:

#. Select ``Log Plotter`` from the ``View Selector`` (see [[Views]]).
#. If you have not previously plotted a block, IBEX displays an empty view, prompting you to select a block.  If you have already plotted a block, IBEX restores the graph.
#. To plot a block, simply right-click on a block displayed in the Blocks & Groups view at the top of the IBEX window.
#. Right-clicking displays a pop-up menu.  Choose``Display block history`` from the menu.
#. IBEX displays a graph of the selected block as a function of time.

The graph axes will automatically adjust to the range of values that the selected block has experienced.  The graph axes are labelled with the name of the underlying PV (remember, blocks are aliases to PVs).

Along the top of the graph are a series of buttons which allow you to adjust the appearance of the graph. For more advanced adjustments, you can right-click and select 'Open Properties Panel' which will open a panel to the right of the graph (by default), which give you more granular control of the appearance of your graph or plot.

Plot a Graph of a PV
--------------------

You can choose a PV to be plotted from any OPI, in the same way as choosing a block.  Simply right-click on the PV and select ``Display block history`` from the menu.