There are two ways of running scripts in IBEX - locally, and on the IBEX server.

Scripting in IBEX is done using genie\_python. The `genie\_python reference manual`_ gives a full account of what functions are available in genie\_python.

This page is intended to give a broad guide to scripting for the
beginner and novice user. For a more in-depth discussion, see our [[genie_python and IBEX training course|genie_python-and-Ibex-(Introduction)]].

- [[Script Server]]
- [[Plotting Using Matplotlib|Matplotlib]]
- [[genie_python Commands]]
- [[Pre and Post Command Hooks]]
- [[Converting Open GENIE to genie_python]]
- [[Creating and running scripts]]
- [[Block names helper]]
- [[Tips and Examples]]
- [[The Scripting Console]]
- [[Using Futurize]]
- [[Script Generator]]
- [[Error Checking Troubleshooting]]

There is some specific [[scripting advice for the Muon Front End|Guidance on Writing Scripts for the Muon Front End]]

If you are new to Python, the Mantid team has created an excellent `Introduction to Python 
<http://www.mantidproject.org/Introduction_To_Python>`_ on the Mantid website.

.. _`genie\_python reference manual`: http://shadow.nd.rl.ac.uk/genie\_python/sphinx/genie\_python.html