
*   Sets the value for a particular block

    + Assumes that either a setpoint exists for the underlying value or the block itself points at a setpoint.

*   Blank lines between list items are optional, avoid them.

    + If you *do* use them (for items with sub-lists or extra
      paragraphs) put blank lines between *all* items at that level.