.. _WhatIsIBEX:

What is IBEX
============

IBEX is the new instrument control program, it is intended to replace SECI. Most device control is curerntly performed using LabVIEW while LabVIEW will not disappear entirely we will be using EPICS for most deviec control. When LabVIEw is requierd ,i it will be wrapped in EPICS.

`IBEX and SECI Differences`_

IBEX and SECI Similarities
--------------------------

Both IBEX and SECI have block and dashboard

IBEX and SECI Differences
--------------------------

IBEX is client-server based, whihc means that the IBEX GUI is itself not the instrument control program. You can thus close the IBEX GUI without stopping control of devices, and also run multiple instances of the GUI on the same or different computers
